spring:
  application:
    name: demo

  datasource:
    url: ${DB_URL}  # jdbc:mariadb://10.10.10.100:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME} # sjb
    password: ${DB_PASSWORD} # qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
